services:
  web:
    container_name: why-is-it-green-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_NUMBER: 1
        GIT_SHA: 7f3c9ab
    environment:
      ENVIRONMENT: development
    ports:
      - '8080:80'
    restart: unless-stopped
