name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Ensure tag commit is on allowed branch
        run: |
          git fetch --all

          if git branch -r --contains $GITHUB_SHA | grep -E 'origin/(main|release/)' ; then
            echo "Tag commit is on an allowed branch."
          else
            echo "Tag commit is NOT on main or release/* - Failing."
            exit 1
          fi

      - name: Extract version from tag
        run: |
          TAG=${GITHUB_REF_NAME}
          VERSION_FROM_TAG=${TAG#v}

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION_FROM_TAG=$VERSION_FROM_TAG" >> $GITHUB_ENV

          echo "Extracted tag: $TAG"
          echo "Version from tag: $VERSION_FROM_TAG"

      - name: Validate tag version matches package.json
        run: |
          VERSION_FROM_PACKAGE=$(node -p "require('./package.json').version")

          echo "Version from tag: $VERSION_FROM_TAG"
          echo "Version from package.json: $VERSION_FROM_PACKAGE"

          if [ "$VERSION_FROM_TAG" != "$VERSION_FROM_PACKAGE" ]; then
            echo "Version mismatch - Failing pipeline."
            exit 1
          fi

      - name: Check if tag already exists on Docker Hub
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/why-is-it-green-web/tags/${TAG})

          if [ "$STATUS" -eq 200 ]; then
            echo "Tag ${TAG} already exists on Docker Hub - Failing."
            exit 1
          fi

      # From here only builds if the tag on docker hub does not exists

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/why-is-it-green-web:${{ env.TAG }}
